### ISSUE TITLE
Dynamin properties in UserAttributes

### ISSUE THREAD

**Issue by antonioturdo** [immobiliare/braze-php-sdk#42]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Since dynamic properties have been deprecated in PHP 8.2, to set custom attributes in the [UserAttributes](https://github.com/immobiliare/braze-php-sdk/blob/main/src/Object/UserAttributes.php) object a setCustomAttribute method will be added in the same class. The custom attributes will be kept in an associative array, and support for their proper serialization in the request will be added.

Before implementation, suggestions for alternative solutions will be considered.

**Comment by JellyBellyDev** [comment]
> Could it make sense to implement this solution directly in the [BaseObject](https://github.com/immobiliare/braze-php-sdk/blob/main/src/Object/BaseObject.php)?

makes sense to me! ;)
